name:                vega
version:             0.1.0.0
github:              "Innf107/vega"
license:             BSD-3-Clause
author:              "Alice Schneider"
maintainer:          "alice@welltypedwit.ch"
copyright:           "2025 Alice Schneider"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/Innf107/vega#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- containers
- unordered-containers
- effectful
- effectful-th
- hashtables
- vector
- megaparsec
- optparse-applicative
- filepath
- time
- prettyprinter
- aeson
- yaml
- witherable
- text
- uuid
- text-builder

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints
- -Wno-name-shadowing
- -Werror=incomplete-patterns
- -Wno-ambiguous-fields

library:
  source-dirs: src

executables:
  vega:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vega

tests:
  vega-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vega

language: GHC2021

default-extensions:
- NoImplicitPrelude
- OverloadedLists
- StrictData
- OverloadedRecordDot
- NoFieldSelectors
- OverloadedStrings
- DuplicateRecordFields
- DataKinds
- TypeFamilies
- BlockArguments
- DerivingVia
- DeriveAnyClass
- LambdaCase
- DefaultSignatures
- PatternSynonyms
- ViewPatterns
- ApplicativeDo
- ImplicitParams
